# This is the .github/workflows/main.yml

name: deploy-heroku-fastapi
on: push

jobs:
  # Check out the following article for more inspiration on setting up a
  # standard CI/CD pipeline for most Python projects:
  # https://jarmos.netlify.app/posts/a-standard-ci-cd-pipeline-for-python-projects/
  deploy:
    # If the test & lint jobs don't pass,
    # the deploy job willn't even execute
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploying to Heroku
        # More details available at:
        # https://github.com/akhileshns/heroku-deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "fastapi-ionic-login"
          heroku_email: "se.asenjo@duocuc.cl"
          healthcheck: "https://<PROJECT-NAME>.herokuapp.com/"
          rollbackonhealthcheckfailed: true
